# Maven

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    mavenDirectory: 

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

- script: mvn package
  displayName: package

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/home/vsts/work/1/s/target/hotelManagement.war' 
    artifactName: 'myWebsiteName' 


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Free Trial (069970bb-164a-4417-be3d-7fbf5bf5b111)'
    appType: 'webApp'
    WebAppName: 'ASDHotel'
    packageForLinux: '$(System.DefaultWorkingDirectory)/_ZihanZheng258.hotelManagement/myWebsiteName/hotelManagement.war'

